spring:
  servlet:
    multipart:
      enabled: false
  datasource:
    name: file-service
    url: jdbc:mysql://example.com:3306/fileService?autoReconnect=true&useUnicode=yes&useSSL=false&characterEncoding=UTF-8
    username: example
    password: example
    sql-script-encoding: UTF-8
    platform: mysql
    continue-on-error: false
    separator: //
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-open-prepared-statements: 20
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: select 'x'
      soft-min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-idle: 10
      max-idle: 10
      initial-size: 15
      max-total: 100

server:
  port: 65512
#  port: 443
#  ssl:
#    key-store: cert/files.pfx
#    key-store-password: example
#    key-store-type: PKCS12
  undertow:
    io-threads: 2
    worker-threads: 8
    buffer-size: 1024
    direct-buffers: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload:
  file-dir: files
  tmp-dir: tmps
  # 上传内存缓冲 128M
  ups-buffer: 134217728
  # 下载内存缓冲 32M
  get-buffer: 33554432
  # 每次读取的bytes 1M
  read-bytes: 1048576
  # md5校验后 上传凭证的使用有效时间
  timeout: 500000
  # 256M
  file-max: 268435456
  # 288M
  size-max: 301989888
